### ISSUE TITLE
'A facade root has not been set.'

### ISSUE THREAD

**Issue by edgreenberg** [santigarcor/laratrust#69]
This is running 4.0.0-rc.1

In artisan tinker I can do this:

```edg@arthur untitled $ artisan tinker
Psy Shell v0.7.2 (PHP 5.6.27 — cli) by Justin Hileman
>>> use App\Permission
=> null
>>> $p=new Permission()
=> App\Permission {#674}
>>> 
```

But in my first attempt to use this... in a test...

```
<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use App\User;
use App\Permission;


class TestAssign extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testAssign()
    {
        $p=new Permission();
        $this->assertTrue(true);
    }
}

```
I get 
```
/usr/bin/php /tmp/ide-phpunit.php --no-configuration TestAssign /home/edg/PhpstormProjects/untitled/tests/TestAssign.php
Testing started at 4:49 AM ...
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'A facade root has not been set.' in /home/edg/PhpstormProjects/untitled/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:210
Stack trace:
#0 /home/edg/PhpstormProjects/untitled/vendor/santigarcor/laratrust/src/Laratrust/LaratrustPermission.php(38): Illuminate\Support\Facades\Facade::__callStatic('get', Array)
#1 /home/edg/PhpstormProjects/untitled/vendor/santigarcor/laratrust/src/Laratrust/LaratrustPermission.php(38): Illuminate\Support\Facades\Config::get('laratrust.permi...')
#2 /home/edg/PhpstormProjects/untitled/tests/TestAssign.php(19): Laratrust\LaratrustPermission->__construct()
#3 /home/edg/PhpstormProjects/untitled/vendor/phpunit/phpunit/src/Framework/TestSuite.php(450): TestAssign->testAssign()
#4 /home/edg/PhpstormProjects/untitled/vendor/phpunit/phpunit/src/Framework/TestSuite.php(855): PHPUnit_Framework_TestSuite::createTest(Object(ReflectionClass), 'testAssign')
#5 /home/edg/PhpstormProjects/untitled/vendor/phpunit/phpunit/src in /home/edg/PhpstormProjects/untitled/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 210

Process finished with exit code 255
```

I followed the installation instructions pretty carefully.

**Comment by edgreenberg** [comment]
Not a package problem. Withdrawn.
